from pydantic import BaseModel, ConfigDict
from datetime import datetime

# MEETING CREATION SCHEMA (MeetingCreate)
# data sent by frontend
class MeetingCreate(BaseModel):
    title: str
    description: str | None = None
    scheduled_at: datetime
    duration: int
# data generated by backend
# id, meeting_id, invite_link, status, created_at

# RESPONSE SCHEMA
# represents what the API sends back to the frontend
class MeetingResponse(BaseModel):
    id: int
    meeting_id: str
    title: str
    description: str | None = None
    scheduled_at: datetime
    duration: int
    invite_link: str
    status: str
    created_at: datetime

    # Allow Pydantic to read values directly from
    # SQLAlchemy ORM model attributes.
    model_config = ConfigDict(from_attributes=True)